# Code to plot energy potential vs z-dimension in order to analyze dipole effects in the system

import pandas as pd
import matplotlib.pyplot as plt

avg_dat_file = 'avg.dat' # Introduce the name of the .dat file generated when running the avg.in script using the average.x program

# Read the avg.dat file generated by average.x program
df = pd. read_csv(avg_dat_file, sep='\s+', header=None)
#Rename the column headers
df.columns = ['Column_0', 'Column_1', 'Column_2']

#Recover the atomic coordinates into a list (z_dimension) and convert the units from Bohr to Angstrom
z_dimension = df['Column_0']/1.88973
#Recover the potential values (y_axis)
potential = df['Column_2']

## Plot potential(column 2) vs z_dimension(column 0) ##


plt.plot(z_dimension, potential, marker='', linestyle='-', color='green')
plt.xlim(0, 78.57) # Adjust these values accordingly
plt.xlabel('Z dimension ($\\AA$)')
plt.ylabel('>')
plt.title('Planar avg of electrostatic potential along z direction')
#plt.legend()  # Show legend with labels
plt.savefig('potential_vs_zdimension.png', dpi=400)  # Change the filename and dpi as needed
plt.show()
